"""empty message

Revision ID: d8181d9c39a5
Revises: 
Create Date: 2018-08-08 12:22:07.538612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8181d9c39a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('weather')
    op.drop_table('people')
    op.drop_table('city')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('sno', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('sname', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=2), autoincrement=False, nullable=True)
    )
    op.create_table('city',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('people',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('weather',
    sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('temp_lo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prcp', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
